config/routes.rb
Rails.application.routes.draw do
  

  resources :comments
  
  root :to =>'tops#index'

  get "tops/index" => "tops#index"

  resources :contacts

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    collection do
        post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  resources :joins, only: [:create, :destroy]

  resources :events do
      collection do
        post :confirm
      end
  end
  root to: 'events#index'
  get 'search', to: 'events#search'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length:{maximum: 30}
    validates :email, presence: true, length:{maximum: 80} ,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_save{email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}

    has_many :event, dependent: :destroy
    has_many :comments
    has_many :favorites, dependent: :destroy
    has_many :favorite_events, through: :favorites, source: :event
    has_many :joins, dependent: :destroy
    has_many :join_events, through: :joins, source: :event

    mount_uploader :icon_image, IconImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_infomation, only: [:edit, :update]

  def new
    if params[:back]
      @user = User.new(user_params)
      @user.icon_image.retrieve_from_cache! params[:cache][:icon_image]
    else
      @user = User.new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def show
    @user = User.find(params[:id])
    @favorites_events = @user.favorite_events.all
    @joins_events = @user.join_events.all
    #join用も入れる
  end

  def create
    @user = User.new(user_params)
    @user.icon_image.retrieve_from_cache!  params[:cache][:image]
    if @user.save
      redirect_to new_session_path, notice:"新たにユーザー情報を登録しました！"
    else
      render'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_image, :icon_image_cache)
    end

    def set_user_infomation
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_users_path

        elsif action_name == 'edit'
            user_path

        end
    end
end

app/views/users/_form.html.erb
<div class="text-center">
<%= form_with(model: @user, local: true, url: user_choose_new_or_edit) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
    <p class="new_icon_lable"><%= form.label :icon_image %></p>
    <p class="new_icon_image"><%= form.file_field :icon_image, id: :@user_icon_image %></p>
    <%= image_tag(@user.icon_image.url) if @user.icon_image.url %>
    <%= form.hidden_field :icon_image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ユーザー詳細画面にもどる", user_path(@user.id) %>
</div>

app/views/users/confirm.html.erb
<div class="text-center">
<h1>確認画面</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :password %>
  <%= form.hidden_field :password_confirmation %>
  <%= hidden_field_tag :"cache[image]",@user.icon_image.cache_name %>

  <p>名前:<%= @user.name %></p>
  <p>メールアドレス:<%= @user.email %></p>
  <p>
    <%= image_tag(@user.icon_image.url) %>
  </p>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= hidden_field_tag :"cache[icon_image]",@user.icon_image.cache_name %>
  <%= form.submit "戻る", name: "back" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>ユーザー情報を編集する</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container text-center">

<h1>Sign up</h1>

<%= form_with(model: @user, local: true, url:confirm_users_path) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="alert alert-warning" role="alert"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_email">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_password">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_password_confirmation">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="new_icon">
    <p class="new_icon_lable"><%= form.label :icon_image %></p>
    <p class="new_icon_image"><%= form.file_field :icon_image, id: :@user_icon_image %></p>
    <%= image_tag(@user.icon_image.url) if @user.icon_image.url %>
    <%= form.hidden_field :icon_image_cache %>
  </div>

  <%= form.submit "Create my account" %>

<% end %>
</div>

app/views/users/show.html.erb
<div class="text-center">
<h4 class="user_infomation"><%= @user.name %></h4>
<div class="user_img">
  <%= image_tag @user.icon_image %>
</div>
<p class="user_infomation">email: <%= @user.email %></p>
<h3 class="user_infomation">
  <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class: 'far fa-edit' %>
</h3>

<div >
  <table class=" table-hover" border="1" >
  <h3>お気に入りイベント一覧</h3>
  <% if !@favorites_events.nil? %>
    <% @favorites_events.each do |favorites_event| %>
    <div class="text-center">
      <tr>
        <th colspan="2">ユーザー名</th>
        <th>お気に入りしたイベントタイトル</th>
        <th>お気に入りしたイベント本文</th>
      </tr>
      <tr>
        <td class="index_favorite_event"><%=favorites_event.user.name %></td>
        <td class="index_favorite_event user_img"><%= image_tag favorites_event.user.icon_image %></td>
        <td class="index_favorite_event"><%=link_to favorites_event.title , event_url %></td>
        <td class="index_favorite_event"><%= favorites_event.content %></td>
      </tr>
    <% end %>
  <% end %>
  </div>
  </table>
</div>
  
 <br></br>
 
<div>
 <table class=" table-hover" border="1">
 <h3>参加イベント一覧</h3>
 <% if !@joins_events.nil? %>
    <% @joins_events.each do |joins_event| %>
    <div class="text-center">
      <tr>
        <th colspan="2">ユーザー名</th>
        <th>参加するイベントタイトル</th>
        <th>参加するイベント本文</th>
      </tr>
      <tr>
        <td class="index_favorite_event">ユーザー名:<%=joins_event.user.name %></td>
        <td class="index_favorite_event user_img"><%= image_tag joins_event.user.icon_image %></td>
        <td class="index_favorite_event">タイトル:<%=link_to joins_event.title , event_url %></td>
        <td class="index_favorite_event">本文:<%= joins_event.content %></td>
      </tr>
    <% end %>
  <% end %>
  </div>
  </table>
</div>
  
</div>
</div>