config/routes.rb
Rails.application.routes.draw do
  

  resources :comments
  
  root :to =>'tops#index'

  get "tops/index" => "tops#index"

  resources :contacts

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    collection do
        post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  resources :joins, only: [:create, :destroy]

  resources :events do
      collection do
        post :confirm
      end
  end
  root to: 'events#index'
  get 'search', to: 'events#search'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :etag_list, presence: true
    validates :area, presence: true
    validates :content, presence: true, length: { in: 1..500 }
    validates :image, presence: true
  
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :comment_users, through: :comments, source: :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    has_many :joins, dependent: :destroy
    has_many :join_users, through: :joins, source: :user

    mount_uploader :image, ImageUploader
    acts_as_taggable_on :etags
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :show, :edit, :update, :destroy]

  def confirm
    @event = Event.new(event_params)
    
    @event.user_id = current_user.id
    render :new if @event.invalid?
  end

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result
  end
  
  
  
  def show
    @favorite = current_user.favorites.find_by(event_id: @event.id)
    @join = current_user.joins.find_by(event_id: @event.id)
    @comments = @event.comments.includes(:user).all
    @comment  = @event.comments.build(user_id: current_user.id) if current_user
  end

  def new
    if params[:back]
      @event = Event.new(event_params)
      @event.image.retrieve_from_cache! params[:cache][:image]
    else
      @event = Event.new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice:"投稿を削除しました！"
  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.image.retrieve_from_cache!  params[:cache][:image]
    if @event.save
      redirect_to events_path, notice: "投稿しました！"
      NoticeMailer.notice_mailer(@event).deliver
    else
      render 'new'
    end
  end

  private
    def event_params
      params.require(:event).permit(:title, :content, :image, :image_cache, :etag_list, :area)
    end
   
    def set_event
      @event = Event.find(params[:id])
    end

    def login_check
      if !current_user
        render("/sessions/new")
      end
    end

end

app/helpers/events_helper.rb
module EventsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_events_path

        elsif action_name == 'edit'
           event_path

        end
    end
end

app/views/events/_form.html.erb
<div class="container  text-center">
<%= form_with(model: @event, local: true, url: choose_new_or_edit) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @event.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br></br>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content, id: :content %>
  </div>
  <br></br>
  <div class="field text-center">
    <%= form.label :image%>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    
  </div>
  <br></br>
   <div>
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>
  <br></br>
  <div class='field'>
    <%= form.label :e_tag, 'タグ（カンマ区切りで入力）' %><br/>
    <%= text_field_tag 'event[etag_list]', @event.etag_list.join(',') %>
  </div>
  
  <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
    NEW
  <% end %>
<% end %>

<%= link_to "イベント一覧画面にもどる", events_path %>
</div>

app/views/events/_search_form.html.erb
    <%= search_form_for @search do |f| %>
      <%= f.label :title, "イベント名" %>
      <%= f.search_field :title%>
      <br>
      <%= f.label :area, "地名" %>
      <%= f.search_field :area %>
      <div class="actions"><%= f.submit "Search" %></div>
    <% end %>

app/views/events/confirm.html.erb
<div class="text-center">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @event, url: events_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :area %>
  <%= form.hidden_field :etag_list %>
  <%= hidden_field_tag :"cache[image]",@event.image.cache_name %>
  
  <p>タイトル:<%= @event.title %></p>
  <p>本文:<%= @event.content %></p>
  <p>地名:<%= @event.area %></p>
  <p>タグ:<%= @event.etag_list %></p>

 
  <p>
    <%= image_tag(@event.image.url) %>
  </p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @event, url: new_event_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :area %>
  <%= form.hidden_field :etag_list %>
  <%= hidden_field_tag :"cache[image]",@event.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>
</div>

app/views/events/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/events/index.html.erb
<div>
<h1>Products</h1>
<p>空白で検索すると一覧が表示されます</p>


<%= search_form_for @q do |f| %>
  <%= f.label :title_cont,"イベント名" %>
  <%= f.search_field :title_cont %>
  <%= f.label :area_cont,"地名" %>
  <%= f.search_field :area_cont %>
  <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
  <i class="fa fa-search"></i>検索
<% end %>

<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :NAME) %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>ユーザー名:<%= event.user.name %></td>
        <td>タイトル:<%= link_to event.title , event_path(event.id)%></td>
        <td>地名:<%= event.area %></td>
        <td>タグ:<%= event.etag_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="row container">
<% @events.each do |event| %>
<div class="text-cente events-index-item cl-xs-9 cl-xs-pull-1 media"
style=" height:250px; background:white;">
      
            <div class="e_user_img media-left">
              <%= image_tag event.user.icon_image %>
            </div>
            
            <div class="media-body">
              <div class="e-user-name">
                <h1>
                <%= event.user.name %>
                </h1>
              </div>
              <div class="e_area">
                <h3>
                <%= event.area %>
                </h3>
              </div>
              <div class="e_title">
                <h2>
                <%= link_to event.title , event_path(event.id)%>
                </h2>
              </div>
            </div>
            
          </tr>
      </table>
</div>     
<% end %>
</div>     

app/views/events/new.html.erb
<h2>投稿する</h2>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row container">
  <div class="col-xs-6 media">
    <div class="media-left user_img">
      <%= image_tag @event.user.icon_image %>
      <div class="media-body">
      <h1 class="media-heading">
        <%= @event.user.name %>
      </h1>
      </div>
    </div>
    <%= image_tag @event.image %>
    <div class="media-body">
    <h2>
      イベントタイトル:
      <%= @event.title %>
    </h2>
    <h3>
      本文:
      <%= @event.content %>
    </h3>
    <h3>
      地名:
      <%= @event.area %>
    </h3>
    <h4>
      タグ:
      <%= @event.etag_list %>
    </h4>
    <h4>
      参加人数:
      <%= @event.joins.count %>
    </h4>
    <h4>
      お気に入り数:
      <%= @event.favorites.count %>
    </h4>
    </div>
  </div>
  
  <div class="col-xs-6">
  <h1>コメント一覧</h1>
  <% @comments.each do |comment| %>
    <div class="comment_index_item">
      <strong><%= comment.user.name %></strong>
      <br />
      <h4><%= comment.body %></h4>
      <p><%= comment.created_at%></p>
      <% if comment.user == current_user %>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete %></p>
      <% end %>
    </div>
  <% end %>
  <% if logged_in? %>
    <%= render 'comments/form' %>
  <% end %>
  </div>
    
    <% if @event.user == current_user %>
      <h4>
        <%= link_to '編集', edit_event_path(@event.id), class: 'far fa-edit' %>
      </h4>
      <h4>
        <%= link_to '削除', event_path(@event.id), method: :delete,
        data: { confirm: '本当に削除していいですか？' }, class: 'far fa-trash-alt'%>
      </h4>
    <% end %>
    
    <div class="col-xs-6 media">
    <% unless @event.user == current_user %>
      <% if @join.present? %>
      <h2>
          <%= link_to 'キャンセルする', join_path(event_id: @event.id), method: :delete%>
      </h2>
      <% else %>
      <h2>
          <%= link_to '参加する', joins_path(event_id: @event.id), method: :post%>
      </h2>
      <% end %>
    <% end %>


    <% unless @event.user == current_user %>
      <% if @favorite.present? %>
      <h2>
          <%= link_to 'お気に入り解除', favorite_path(event_id: @event.id), method: :delete%>
      </h2>
      <% else %>
      <h2>
          <%= link_to 'お気に入り', favorites_path(event_id: @event.id), method: :post%>
      </h2>
      <% end %>
    <% end %>
  </div>
</div>